### ISSUE TITLE
Crash on non ascii output

### ISSUE THREAD

**Issue by liiight** [liiight/pytest-docs#1]

**Comment by liiight** [comment]
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/orcarmi/PycharmProjects/notifiers/venv/lib/python3.6/site-packages/_pytest/main.py", line 178, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/orcarmi/PycharmProjects/notifiers/venv/lib/python3.6/site-packages/_pytest/main.py", line 215, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/orcarmi/PycharmProjects/notifiers/venv/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/orcarmi/PycharmProjects/notifiers/venv/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/orcarmi/PycharmProjects/notifiers/venv/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/Users/orcarmi/PycharmProjects/notifiers/venv/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/orcarmi/PycharmProjects/notifiers/venv/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/orcarmi/PycharmProjects/notifiers/venv/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/orcarmi/PycharmProjects/notifiers/venv/lib/python3.6/site-packages/pytest_docs/plugin.py", line 29, in pytest_runtestloop
INTERNALERROR>     file.write(out)
INTERNALERROR> UnicodeEncodeError: 'ascii' codec can't encode characters in position 7909-7910: ordinal not in range(128)
```
